FROM node:alpine
COPY . /team9-project
WORKDIR /team9-project/FrontEnd/myfirstapp
RUN npm install
EXPOSE 3000
CMD npm start

# use this command to run docker
# docker run -it -p 3000:3000 s3841649/group9_sept